# Generated by Django 3.2.18 on 2023-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230311_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=128)),
                ('store_address', models.CharField(max_length=128)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('store_number', models.CharField(max_length=128)),
            ],
        ),
    ]
