# Generated by Django 3.2.18 on 2023-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
    ]
